name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow-gpu
  # - tensorflow-gpu=2.6.0
  - opencv
  - tqdm
  # - pip:
  #     - some-package-not-available-in-conda
